"""Add PackageTracking table and update Transaction relationships

Revision ID: 9e538f2fbd2e
Revises: fae334151d1b
Create Date: 2024-08-09 12:25:55.324701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e538f2fbd2e'
down_revision: Union[str, None] = 'fae334151d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_tracking',
        sa.Column('package_tracking_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('brief_submitted', sa.Boolean(), nullable=True, default=False),
        sa.Column('brief_attachment_link', sa.String(), nullable=True),
        sa.Column('discovery_call_booked', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('discovery_call_link', sa.String(), nullable=True),
        sa.Column('onboarding_call_booked', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('onboarding_call_link', sa.String(), nullable=True),
        sa.Column('offboarding_call_booked', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('offboarding_call_link', sa.String(), nullable=True),
        sa.Column('project_completed_status', sa.Boolean(), nullable=False, server_default='false'),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('package_tracking_id')
    )
    op.create_index(op.f('ix_package_tracking_package_tracking_id'), 'package_tracking', ['package_tracking_id'], unique=False)

    # Add the new relationship to the transactions table
    op.add_column('transactions', sa.Column('package_tracking_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_package_tracking_transaction', 
        'package_tracking', 'transactions', 
        ['transaction_id'], ['transaction_id'], 
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_package_tracking_transaction', 'package_tracking', type_='foreignkey')
    op.drop_column('transactions', 'package_tracking_id')
    op.drop_index(op.f('ix_package_tracking_package_tracking_id'), table_name='package_tracking')
    op.drop_table('package_tracking')
    # ### end Alembic commands ###
