"""Create recommendation_briefs table with foreign key to users by email

Revision ID: dd8923211ba1
Revises: fa1a5a97df3c
Create Date: 2024-08-14 15:26:38.491396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8923211ba1'
down_revision: Union[str, None] = 'fa1a5a97df3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recommendation_briefs',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('company_name', sa.String(), nullable=False),
        sa.Column('type_of_industry', sa.String(), nullable=False),
        sa.Column('company_size', sa.String(), nullable=False),
        sa.Column('website_url', sa.String(), nullable=True),
        sa.Column('contact_person_name', sa.String(), nullable=False),
        sa.Column('contact_email', sa.String(), nullable=False),
        sa.Column('contact_phone_number', sa.String(), nullable=False),
        sa.Column('current_specific_business_challenges', sa.String(), nullable=False),
        sa.Column('previously_implemented_digital_solutions', sa.String(), nullable=False),
        sa.Column('solution_and_outcome_description', sa.String(), nullable=False),
        sa.Column('target_audience', sa.String(), nullable=False),
        sa.Column('target_audience_age_group', sa.String(), nullable=False),
        sa.Column('target_audience_gender', sa.String(), nullable=False),
        sa.Column('target_audience_location', sa.String(), nullable=False),
        sa.Column('target_audience_interest', sa.String(), nullable=False),
        sa.Column('existing_audience_persona_available', sa.Boolean(), nullable=False),
        sa.Column('existing_audience_persona_description', sa.String(), nullable=False),
        sa.Column('budget_projection_range', sa.String(), nullable=False),
        sa.Column('preferred_solutions', sa.String(), nullable=False),
        sa.Column('main_competitors', sa.String(), nullable=False),
        sa.Column('competitor_website_links', sa.String(), nullable=True),
        sa.Column('competitor_like_and_dislike', sa.String(), nullable=False),
        sa.Column('additional_context', sa.String(), nullable=True),
        sa.Column('relevant_document_link', sa.String(), nullable=True),
        sa.Column('news_letter_subscription', sa.Boolean(), nullable=False, server_default="FALSE"),
        sa.Column('user_email', sa.String(), sa.ForeignKey('users.email'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_briefs')
    # ### end Alembic commands ###
